site_name: Leihs Manual
# NOTE: setting the correct path here is important (relative links etc), but the build output should work on any domain/hostname
site_url: "https://leihs.github.io/manual/"

site_dir: "site"
markdown_extensions: [toc, tables, fenced_code, footnotes]

nav:
  - "Einleitung": "index.md"
  - "Suchen & Bestellen": "suchen-bestellen.md"
  - "Abholen & Zurückbringen": "ausgeben-and-zurucknehmen.md"
  - "Genehmigen & Herausgeben": "genehmigen-and-herausgeben.md"
  - "Inventarisieren & Verwalten": "inventarisieren.md"
  - "Admin": "admin.md"

  - "External Links":
      - "Leihs on GitHub": "https://github.com/leihs"
