site_name: My Docs

nav:
  - "Einleitung": "index.md"
  - "Abholen & Zurückbringen": "ausgeben-and-zurucknehmen.md"
  - "Genehmigen & Herausgeben": "genehmigen-and-herausgeben.md"
  - "Inventarisieren & Verwalten": "inventarisieren.md"
  - "Admin": "test-1.md"
